### ISSUE TITLE
Allow Distribution ID

### ISSUE THREAD

**Issue by Christoph-Schabert** [silvermine/serverless-plugin-cloudfront-lambda-edge#1]
Hi,
we want to enable cloud edge functions but the cloudfront distribution is part of an other microservice.
Is it possible to add an optional parameter to the configuration
e.g.
         distribution_id 

instead of the logical name?

**Comment by jthomerson** [comment]
@Christoph-Schabert I'd be happy to review a pull request that incorporated a feature like this. To meet our coding standards the name in the config would be `distributionID` - making it so that you could supply either `distribution` (logical name) or `distributionID`.

We don't have time to add this feature ourselves currently, but if you work on a PR for it, we can review it and cut a release. Information on contributing can be found here: https://github.com/silvermine/silvermine-info#contributing

**Comment by grancalavera** [comment]
Hi @jthomerson @Christoph-Schabert, I was about to ask the same question, since I already have a distribution created using a separate CloudFormation stack which I would prefer not to manage using the Serverless Framework. 

Is this feature still up for grabs? If that's the case I'd be happy to give it a go.

**Comment by grancalavera** [comment]
Nevermind, I didn't notice @geoffdutton already got it covered. Any chance we can get this feature merged?

**Comment by hustshawn** [comment]
Actually, when I use the edge, I just wanna lambda to handle an EXISTING CloudFront Distribution instead of create a new one, so probably the better way should be able to specify the `distributionID` or `arn` of the existing distribution. How can it be achieved use this plugin? @jthomerson

**Comment by jthomerson** [comment]
@hustshawn @Christoph-Schabert this sounds like a valid usecase, but I'm not sure that it's one this plugin can support. The new CloudFormation support for Lambda@Edge makes it so that the `LambdaFunctionAssociations` are defined on the `CloudFront::Distribution` properties. Thus, they must be defined as part of the same stack that contains the distribution. To avoid other issues (like duplicate CloudFront distribution updates) that were incumbent on v1.0 of this plugin, v2.0 will use the newly-released CloudFormation support for Lambda@Edge (see #7).

It sounds like what you want to accomplish would suffer from the same problems that v1.0 of this plugin had - requiring multiple updates to the distribution, etc. Of course, that may be satisfactory for your usecase. I'd suggest you create a separate plugin (perhaps forking v1.0 of this plugin as your model) to fill the need of that usecase. This plugin (v2.0) will be very slim, so I don't think it's the right direction to go for it to be the "support everything" plugin for CloudFront / Lambda@Edge.

Thanks for reaching out and sorry for the delayed response.
