### ISSUE TITLE
Question: use a distribution ID as the distribution?

### ISSUE THREAD

**Issue by marcelpanse** [silvermine/serverless-plugin-cloudfront-lambda-edge#14]
Hi,
We have a situation where are already using AWS extensively (lambda, edge, apig, s3, cf, etc). We are now moving to the serverless framework instead of apex that we used so far. We migrated all the lambda's already which is working fine, now we want to deploy the edge functions using serverless. However, I can only reference a defined cloudformation distribution name as the distribution of the function. This is not an option for us, since our CF is fairly complicated with 50 behaviors and multiple origins. I don't want to configure all of that in serverless at this moment, also I think this is not possible without deploying an entirely new CF distribution (which would mean we lose cache hits, etc). 

Anyway, I was wondering if we could just use a distribution ID in the distribution field instead? Is there a reason why this shouldn't or can't be done? If not, I could make a PR.

**Comment by marcelpanse** [comment]
I think it could be much simpler. The CF distro we have is not in any stack, it was just manually added. 
If it is not possible to reference a distribution by ID like you explained, then a simpler solution would be to just not associate the function automatically with CF. 
Basically, I just want to deploy the function, manually test it, and then associate it manually with the CF distro. I think this could be achieved with your plugin by simply adding an option to not associate the edge function (not call _handleSingleFunctionAssociation() ?)

Does that make sense to add as an option?

**Comment by shaunc** [comment]
It seems that both creating a distribution together with lambda functions and updating an existing distribution by modifying lambda functions are useful behaviors. (I ended up using this to learn how to configure my distribution and lambda functions to use lambda@edge because there are a number of gotchas for the newbie like myself.) Perhaps updating existing could be an alternate behavior of the plugin?

**Comment by jthomerson** [comment]
Sorry guys, closing this issue. I believe strongly in the single responsibility principle. This plugin's single responsibility is - as its name indicates - to make Lambda functions work with Lambda@Edge, with CloudFront. The entire plugin is 163 lines of code; part of the reason it's so simple is because it only does one thing, and does it well.

There's a lot of explanation above about how you could make a plugin targeting your specific usecases. You can fork this one, rename it, and use it as a base, or copy and paste the code from either v1 or v2 of this plugin into your own.

**Comment by ossareh** [comment]
@marcelpanse & @shaunc I too had a similar challenge; specifically I don't yet have the operational confidence in serverless to know what will inadvertently re-create a set of resources - in the case of a CloudFront distribution that takes so long, and causes some many knock on issues that while this plugin does much of what I want, it doesn't do it all.

As such I created my own based on the feedback in the first comment from @jthomerson : https://github.com/ossareh/serverless-lambda-edge - it's not being published to npm yet (happy to take PR's on that). In short you `sls deploy --stage production` and then `aws cloudformation --region us-east-1 list-exports` - take the arn and use it in your CloudFront distribution (which I manage in CloudFront away from serverless).
