### ISSUE TITLE
Question: can I use this for auth & to set signed cookies

### ISSUE THREAD

**Issue by shaunc** [silvermine/serverless-plugin-cloudfront-lambda-edge#17]
I am wondering if this is the right tool to deploy authorization functionality for cloud front serving restricted S3 content. It would seem that what I need to do is provide one function to check credentials, and another to add signed cookies... I am having trouble finding good examples of this using google, however, and (having other serverless functions deployed, but not having used cloudfront before) wonder if there is something I'm missing. Any advice or examples would be appreciated. (This could be a documentation feature request .... :)) ... Thanks!

**Comment by jthomerson** [comment]
@shaunc yes, you could use this plugin to add Lambda@Edge functions to your CloudFront distribution that provide authorization functionality. The thing is, this plugin is not a good place to add the documentation examples that you are requesting. This plugin is about adding Lambda functions to a CloudFront distribution for use as Lambda@Edge functions - regardless of their functionality. There are way too many things you can do with Lambda@Edge to make it feasible to write tutorials for all of them. Since you say you haven't used CloudFront before, I'd suggest starting with one of the myriad of tutorials that AWS provides about setting up a distribution. Once you have that working, then go on to one of their tutorials about Lambda@Edge. For example [their tutorial on A/B testing](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html) involves using cookies.

**Comment by shaunc** [comment]
ok .. that's reasonable ... "myriad of tutorials" -- is accurate. :)
