### ISSUE TITLE
Module fails when real distribution name is used

### ISSUE THREAD

**Issue by cyberfox1** [silvermine/serverless-plugin-cloudfront-lambda-edge#32]
This module is useless unless the function is deployed in the same serverless.yml that contains the distribution resource. Can't even put the distribution Id in the distribution field!

**Comment by jthomerson** [comment]
@cyberfox1 I'm not sure what the point of your opening this issue is. It seems more like an attack on people who are providing free and useful software instead of a valid issue.

If you have a valid issue that you'd like to report or a feature enhancement to suggest, feel free to open an issue using words that are courteous and respectful.
