### ISSUE TITLE
CloudFormation error when deleting stack

### ISSUE THREAD

**Issue by alexcasalboni** [silvermine/serverless-plugin-cloudfront-lambda-edge#6]
When I run `sls remove` I get this error:

```
Lambda was unable to delete arn:aws:lambda:xxx:yyy:function:abc:1 because it is a replicated function.
```

I guess the plugin should manually delete the CloudFront trigger before `sls` deletes the CloudFormation Stack.

**Comment by cbravo** [comment]
+1

**Comment by jthomerson** [comment]
Sorry @alexcasalboni ... not much we can do here. This is an AWS issue. See https://forums.aws.amazon.com/thread.jspa?threadID=260242&tstart=0 and https://forums.aws.amazon.com/ann.jspa?annID=5529. You will encounter this error when you first try to remove a stack because the the removal of the stack triggers the removal of the functions. However, AWS says that after you've removed the CloudFront distribution that refers to the functions, it takes several hours for them to clean up the replicated copies of the function. Only after that happens can the "master" copy of the function be deleted. I've experienced this and note that after you get the error initially, if you wait several hours (although usually I only have to wait about thirty minutes), you should be able to remove the stack. I'm not sure if `sls remove` a second time will work, but removing the stack directly through CloudFormation will then work - I've done that many times.

Note that the same issue can come up when you make a change in your serverless.yml (in your CloudFormation stack) that results in the removal of a function - for instance, renaming it - when that function was associated with a CloudFront distribution. The remedy is the same - wait until all the AWS edge locations have removed the replicas and then try again.

**Comment by iDVB** [comment]
If ever someone hears better support here from AWS please post back here. This limitation is rather silly.
